function [selectedFolder] = OnlineModelSelection(baseFolder)
%OnlineModelSelection Gui window for selecting model folder for online pipeline

GUI.fh = figure('units','normalized',...                   
                'position',[0.2 0.2 0.4 0.3],...
                'menubar','none',...
                'name','User interface',...
                'numbertitle','off',...
                'resize','off');
             
% Set title text
GUI.title = uicontrol('style','text',...                 
                     'unit','normalized',...
                     'position',[0.2 0.75 0.6 0.2],...
                     'string','Choose a model folder if you wish to use the non-default model',...
                     'FontSize',22);
% TODO
GUI.subjectLabel = uicontrol('style','text',...
                             'unit','normalized',...
                             'position',[0.09 0.03 0.2 0.2],...
                             'string', 'Subject Id: ',...
                             'FontSize', 13);
              
GUI.subjectId = uicontrol('style','edit',...
                          'unit','normalized',...
                          'position',[0.275 0.15 0.2 0.1], ...
                          'string', '500');
% Set online toggle button
GUI.default = uicontrol('style','togglebutton',...              
                    'string', '<html>Use Subjects<br>Default Model',...
                    'FontSize',14,...
                    'unit','normalized',...
                    'position',[0.275 0.3 0.2 0.4]);
                 
% Set offline toggle button
GUI.selectModel = uicontrol('style','togglebutton',...              
                    'string', 'Select Model',...
                     'FontSize',14,...
                    'unit','normalized',...
                    'position',[0.525 0.3 0.2 0.4]);

    function closeWindow(varargin)
        uiresume(GUI.fh);
        close(GUI.fh);
    end
    
    function setDefaultModelDir(varargin)
            subjectID = str2double(GUI.subjectId.String);
            selectedFolder = [baseFolder '\' int2str(subjectID) '\' Utils.Config.modelDirName];
            closeWindow()
    end

    function selectModelCallback(varargin)
         selectedFolder = uigetdir('G:\.shortcut-targets-by-id\1EX7NmYYOTBYtpFCqH7TOhhm4mY31oi1O\P300-Recordings', ...
        'Choose model for Online');
        closeWindow();
    end


set(GUI.selectModel, 'callback', {@selectModelCallback});
set(GUI.default, 'callback', {@setDefaultModelDir});

uiwait(GUI.fh);



end

