function [Hz, trialLength, numClasses, subId, numTrials, timeBetweenTriggers, oddBallProb, ...
    calibrationTime, pauseBetweenTrials, triggerBank] = ParametersGui()
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

% location parameters
editor_width = 0.1;
editor_height = 0.1;
text_width = 0.15;
text_height = 0.1;
lables_col_x_pos = [0.05 0.35 0.65];
editor_col_x_pos = [0.2 0.5 0.8];
labels_row_y_pos = [0.65 0.45 0.25];
editor_row_y_pos = [0.67 0.47 0.27];

%% Others
GUI.fh = figure('units','normalized',...
    'position',[0.2 0.3 0.5 0.4],...
    'menubar','none',...
    'name','Parameter setting',...
    'numbertitle','off',...
    'resize','off');

% Set title text
GUI.title = uicontrol('style','text',...
    'unit','normali  zed',...
    'position',[0.2 0.7 0.6 0.2],...
    'string','Set parameters for your system');

% Set confirmation button
GUI.confirm = uicontrol('style','push',...
    'unit','normalized',...
    'position',[0.72 0.08 0.2 0.1],...
    'string','Ok');

% Set impedance button
GUI.Imp = uicontrol('style','push',...
    'unit','normalized',...
    'position',[0.125 0.08 0.2 0.1],...
    'string','Impedance');

% Select trigger bank folder
GUI.bank = uicontrol('style','push',...
    'unit','normalized',...
    'position',[0.42 0.08 0.2 0.1],...
    'string','Select Triggers');


%% Configurations

% Set subID text
[GUI.subIDtxt, GUI.subID] = LabelEditorCreator(...
    [lables_col_x_pos(1) labels_row_y_pos(1) text_width text_height], 'Subject ID', ...
    [editor_col_x_pos(1) editor_row_y_pos(1) editor_width editor_height], '000');

%number of classes
[GUI.nClstxt, GUI.nCls] = LabelEditorCreator(...
    [lables_col_x_pos(1) labels_row_y_pos(2) text_width text_height], '# of classes:',...
    [editor_col_x_pos(1) editor_row_y_pos(2) editor_width editor_height], '2');

%system calibration time
[GUI.calibTxt, GUI.calibrationTime] = LabelEditorCreator(...
    [lables_col_x_pos(1) labels_row_y_pos(3) text_width text_height], 'Calibration Time (sec):', ...
    [editor_col_x_pos(1) editor_row_y_pos(3) editor_width editor_height], '20');

%time between triggers 
[GUI.timeBetweenTriggersTxt, GUI.timeBetweenTriggers] = LabelEditorCreator(...
    [lables_col_x_pos(2) labels_row_y_pos(1) text_width text_height], ['Time between ', sprintf('\n'), 'triggers(sec):'],...
    [editor_col_x_pos(2) editor_row_y_pos(1) editor_width editor_height],'1');

%Oddball Probability
[GUI.trialLengthTxt, GUI.trialLength] = LabelEditorCreator(...
    [lables_col_x_pos(2) labels_row_y_pos(2) text_width text_height], ['Trail Length', sprintf('\n'), '(# of triggers):'], ...
    [editor_col_x_pos(2) editor_row_y_pos(2) editor_width editor_height], '20');

%pause between trials
[GUI.pauseBetweenTrialsTxt, GUI.pauseBetweenTrials] = LabelEditorCreator(...
    [lables_col_x_pos(2) labels_row_y_pos(3) text_width text_height], ['Pause Between', sprintf('\n'), 'Trails (sec):'], ...
    [editor_col_x_pos(2) editor_row_y_pos(3) editor_width editor_height], '10');

%num of trials text
[GUI.nTrialtxt,GUI.nTrial] = LabelEditorCreator(...
    [lables_col_x_pos(3) labels_row_y_pos(1) text_width text_height],'# of trials', ...
    [editor_col_x_pos(3) editor_row_y_pos(1) editor_width editor_height],'10');


%num of trials text
[GUI.oddBallProbTxt, GUI.oddBallProb] = LabelEditorCreator(...
    [lables_col_x_pos(3) labels_row_y_pos(2) text_width text_height],'Oddball probability:', ...
    [editor_col_x_pos(3) editor_row_y_pos(2) editor_width editor_height],'0.2');


% Set Hz
GUI.Hztxt = uicontrol('style','text',...
    'unit','normalized',...
    'position',[lables_col_x_pos(3) labels_row_y_pos(3) text_width editor_height],...
    'string','Sampling rate:');
GUI.Hz    = uicontrol('style','popupmenu',...
    'unit','normalized',...
    'position',[editor_col_x_pos(3) (editor_row_y_pos(3)-0.02) editor_width editor_height],...
    'string',['512';'256';]);

%% Callbacks
triggerBank{1}= './TriggersBank/Sounds1/';
set(GUI.Imp,'callback',{@GUIFiles.OpenImpedanceCallback});
set(GUI.bank,'callback',{@GUIFiles.SelectTriggerBankCallback,triggerBank})

% This function is needed because I couldn't call uiresume as a direct
% callback from the GUI button
    function releaseGui(varargin)
        uiresume(GUI.fh)
    end

set(GUI.confirm, 'callback', {@releaseGui});
%% Wait for user reaction
uiwait(GUI.fh);

%% Extract user input parameters
% Extract sampling rate value
posHz = GUI.Hz.Value;
Hz    = str2double(GUI.Hz.String(posHz,:));
trialLength = str2double(GUI.trialLength.String);
numClasses = str2double(GUI.nCls.String);
subId = str2double(GUI.subID.String);
numTrials = str2double(GUI.nTrial.String);
timeBetweenTriggers = str2double(GUI.timeBetweenTriggers.String);
oddBallProb = str2double(GUI.oddBallProb.String);
calibrationTime = str2double(GUI.calibrationTime.String);
pauseBetweenTrials = str2double(GUI.pauseBetweenTrials.String);
triggerBank = triggerBank{1};

close(GUI.fh);

end

function [label, editor] = LabelEditorCreator(label_pos, lablel_text, editor_pos, editor_text)
%LABELEDITORCREATOR Summary of this function goes here
%   Detailed explanation goes here

label = uicontrol('style','text',...
                  'unit','normalized',...
                  'position',label_pos,...
                  'string', lablel_text);
              
editor = uicontrol('style','edit',...
                   'unit','normalized',...
                   'position',editor_pos, ...
                   'string',editor_text);

end
