function [] = OfflinePipline()
% This functions starts the P300 offline training pipeline

baseFolder = uigetdir('C:/Subjects/', ...
    'Choose Desired Directory for Saving Recordings');

%% Recording Parameter Setting
[is_visual, triggersInTrial, numClasses, subId, numTrials, timeBetweenTriggers, oddBallProb, ...
    calibrationTime, pauseBetweenTrials, triggerBankFolder] = GUIFiles.ParametersGui();


recordingFolder = [baseFolder int2str(subId)];

%% Training
[EEG, fullTrainingVec, expectedClasses, triggersTime] = ...
    OfflineTraining(timeBetweenTriggers, calibrationTime, pauseBetweenTrials, numTrials, ...
                    numClasses, oddBallProb, triggersInTrial, ...
                    triggerBankFolder, is_visual);

save(strcat(recordingFolder, 'trainingSequences.mat'), 'fullTrainingVec');
save(strcat(recordingFolder, 'EEG.mat'), 'EEG');
save(strcat(recordingFolder, 'trainingLabels.mat'), 'expectedClasses');
save(strcat(recordingFolder, 'trainingLabels.mat'), 'expectedClasses');
save(strcat(recordingFolder, 'triggersTime.mat'), 'triggersTime');

parametersToSave = struct('timeBetweenTriggers', timeBetweenTriggers, ...
                           'calibrationTime', calibrationTime, ...
                           'pauseBetweenTrials',pauseBetweenTrials, ...
                           'numTrials', numTrials, ... 
                           'startingNormalTriggers', startingNormalTriggers, ...
                           'numClasses', numClasses, ...
                           'oddBallProb', oddBallProb, ...
                           'triggersInTrial', triggersInTrial, ...
                           'Hz', Hz, ...
                           'mode', is_visual, ...
                           'triggerBankFolder', triggerBankFolder);
save(strcat(recordingFolder, 'parameters.mat'), 'parametersToSave')


%% PreProcessing

processedEEG = Preprocessing(EEG, is_visual, Utils.Config.highLim, Utils.Config.lowLim, ...
                             Utils.Config.downSampleRate, triggersInTrial, Utils.Config.triggerWindowTime, ...
                             Utils.Config.eegChannels, Utils.Config.preTriggerRecTime, timeBetweenTriggers);

save(strcat(recordingFolder, 'processedEEG.mat'), 'processedEEG');
end

