function [] = OfflinePipline()
% OfflinePipline - This functions starts the P300 offline training pipeline
% recording, preprocessing and creating a model

%clear any previous open windows - hopefully.
close all; clear; clc;

baseFolder = uigetdir('G:\.shortcut-targets-by-id\1EX7NmYYOTBYtpFCqH7TOhhm4mY31oi1O\P300-Recordings', ...
    'Choose Desired Directory for Saving Recordings');

%% Recording Parameter Setting
[is_visual, triggersInTrial, numClasses, subId, numTrials, timeBetweenTriggers, oddBallProb, ...
    calibrationTime, pauseBetweenTrials, triggerBankFolder, beforeJitterTime] = GUIFiles.ParametersGui();

currDateTime = strrep(strrep(datestr(now), ':','-'), ' ', '_');
recordingFolder = [baseFolder '\' int2str(subId) '\' currDateTime '\'];
mkdir(recordingFolder);

%% Training
[EEG, trainingVector, trainingLabels, triggersTimes, backupTimes] = ...
    Recording.OfflineTraining(timeBetweenTriggers, calibrationTime, pauseBetweenTrials, numTrials, beforeJitterTime, ...
                              numClasses, oddBallProb, triggersInTrial, ...
                              triggerBankFolder, is_visual);

save(strcat(recordingFolder, 'trainingVector.mat'), 'trainingVector');
save(strcat(recordingFolder, 'EEG.mat'), 'EEG');
save(strcat(recordingFolder, 'trainingLabels.mat'), 'trainingLabels');
save(strcat(recordingFolder, 'triggersTimes.mat'), 'triggersTimes');
save(strcat(recordingFolder, 'backupTimes.mat'), 'backupTimes');

parametersToSave = struct('timeBetweenTriggers', timeBetweenTriggers, ...
                          'calibrationTime', calibrationTime, ...
                          'pauseBetweenTrials',pauseBetweenTrials, ...
                          'numTrials', numTrials, ...
                          'beforeJitterTime', beforeJitterTime, ...
                          'startingNormalTriggers', Utils.Config.startingNormalTriggers, ...
                          'numClasses', numClasses, ...
                          'oddBallProb', oddBallProb, ...
                          'triggersInTrial', triggersInTrial, ...
                          'triggerBankFolder', triggerBankFolder, ...
                          'mode', is_visual, ...
                          'Hz', Utils.Config.Hz, ....
                          'highLim', Utils.Config.highLim, ...
                          'lowLim', Utils.Config.lowLim, ...
                          'pauseBeforeDump', Utils.Config.pauseBeforeDump, ...
                          'preTriggerRecTime', Utils.Config.preTriggerRecTime, ...
                          'triggerWindowTime', Utils.Config.triggerWindowTime, ...
                          'is_visual', is_visual, ...
                          'preTrialPause', Utils.Config.preTrialPause, ...
                          'maxRandomTimeBetweenTriggers', Utils.Config.maxRandomTimeBetweenTriggers, ...
                          'downSampleRate', Utils.Config.downSampleRate);
                           
save(strcat(recordingFolder, 'parameters.mat'), 'parametersToSave');


%% PreProcessing

[splitEEG, meanTriggers, subtractedMean, processedEEG] = preprocessing(EEG, triggersTimes, trainingVector, ...
                                         Utils.Config.preTriggerRecTime, Utils.Config.triggerWindowTime, ...
                                         Utils.Config.downSampleRate);

save(strcat(recordingFolder, 'splitEEG.mat'), 'splitEEG');
save(strcat(recordingFolder, 'meanTriggers.mat'), 'meanTriggers');
save(strcat(recordingFolder, 'subtractedMean.mat'), 'subtractedMean');
save(strcat(recordingFolder, 'processedEEG.mat'), 'processedEEG');

%% Models

modelDir = [baseFolder '\' int2str(subId) '\' Utils.Config.modelDirName '\'];
mkdir(modelDir)
pythonCommand = ['python PythonCode\ModelSearch.py ' recordingFolder ' ' modelDir];
[pyStatus, pyOutput] = system(pythonCommand, '-echo');

%% Close all

close all hidden


end

